### ISSUE TITLE
可以正常在8点签到，但是怎么在另外时间签退呢，要重新fork一个吗

### ISSUE THREAD

**Issue by lliyuhao** [CncCbz/xybSign#28]

**Comment by CncCbz** [comment]
重新创建一个action和secrets，用新的action进行签退

**Comment by CncCbz** [comment]
例如：
1、创建一个Action名为`main.yml`,内容如下
```
name: 签退 # yml文件名
 
on:
  workflow_dispatch:
  schedule:   
    # https://crontab.guru/
    # UTC 时间，中国时区应减 8
    - cron: '0 10 * * *'
 
jobs:
  run-check-in: # 任务名
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: 安装依赖  
        run: |
          npm install

      - name: 运行签到
        run: |
          node ./index.js '${{ secrets.XYB_OUT }}'
```
2、创建一个新的secrets，名为`XYB_OUT`,值为：`username=用户名&password=密码;mode=out;qmsgKey=keykey;qmsgTo=123412445`
